[package]
name = "bio"
version = "0.0.0"
edition = "2018"
authors = ["The Biome Maintainers <humans@biome.sh>"]
build = "../build-biome.rs"
workspace = "../../"

[[bin]]
name = "bio"
doc = false

[dependencies]
# Can we keep these alphabetized? We're not savages.
base64 = "*"
bitflags = "*"
chrono = {version = "*", features = ["serde"]}
ctrlc = "*"
dirs = "*"
env_logger = "*"
flate2 = "*"
futures = { version = "*" }
glob = "*"
biome_api_client = { path = "../builder-api-client" }
biome_common = { path = "../common" }
biome_core = { path = "../core" }
biome-sup-client = { path = "../sup-client" }
biome-sup-protocol = { path = "../sup-protocol", default-features = false }
# We need to lock here since v0.30.0 bumps to a version of pest that fails to build on Windows.
handlebars = { version = "0.29.1", default-features = false }
lazy_static = "*"
libc = "*"
log = "0.4"
pbr = "*"
rants = { version = "0.6.1", git = "https://github.com/habitat-sh/rants.git", features = ["native-tls"] }
reqwest = { version = "*", features = ["blocking", "json", "stream"] }
retry = { git = "https://github.com/habitat-sh/retry", features = ["asynchronous"] }
rustls = "*"
same-file = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*", features = [ "preserve_order" ] }
serde_yaml = "*"
tabwriter = "*"
tar = "*"
termcolor = "*"
thiserror = "*"
anyhow = { version = "*", features = ["backtrace"] }
tokio = { version = "*", features = ["full"] }
toml = { version = "*", features = [ "preserve_order" ] }
url = { version = "*", features = ["serde"] }
walkdir = "*"
rustls-webpki = { version = "*", features = ["alloc"] }
tempfile = "*"


clap = { git = "https://github.com/habitat-sh/clap.git", branch = "v2-master", features = [ "suggestions", "color", "unstable" ] , optional = true}
configopt = { git = "https://github.com/habitat-sh/configopt.git" , optional = true}
structopt = { git = "https://github.com/habitat-sh/structopt.git" , optional = true}

clap_v4 = { version = "4", package = "clap", features = ["env", "derive", "string", "wrap_help"], optional = true }

[dependencies.uuid]
version = "*"
features = ["v4"]

[target.'cfg(windows)'.dependencies]
widestring = "*"
winapi = { version = "^0.3", features = ["winuser", "windef"] }
winreg = "*"

[features]
v2 = [ "clap", "configopt", "structopt" ]
v4 = [ "supported_targets", "clap_v4" ]
default = ["supported_targets", "v2"]
functional = []
supported_targets = ["biome_core/supported_targets"]
