FROM {{base_image}}

{{ #if multi_layer }}
# TODO (CM): If package-per-layer becomes an issue, we could gain a
# bit of headspace by putting all the Supervisor-related packages and
# dependencies in one layer, and then add user packages in subsequent
# layers.
#
# Alternatively, we might take advantage of a Supervisor-only
# container as a base image:
# https://github.com/habitat-sh/habitat/issues/4977
{{ #each packages as |pkg|}}
COPY {{../rootfs}}/bio/pkgs/{{pkg}} /bio/pkgs/{{pkg}}
{{ /each }}
{{ else }}
ADD {{rootfs}}/bio /bio
{{ /if }}

EXPOSE 9631 {{exposes}}
RUN SET BIO_FEAT_OFFLINE_INSTALL=ON && \
    {{ #if environment}}
    {{ #each environment}}
        SET {{@key}}={{{this}}}&& \
    {{ /each}}
    {{ /if}}
    {{bio_path}} pkg install {{installed_primary_svc_ident}}
ENTRYPOINT ["{{bio_path}}", "sup", "run", "{{primary_svc_ident}}"]
