name: release

on:
  release:
    types: [published]

jobs:

  package-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Linux Biome
        run: |
          curl https://raw.githubusercontent.com/biome-sh/biome/master/components/bio/install-linux.sh | sudo bash

      - name: Install Signing Keys
        env:
          HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
        run: |
          bio origin key download biome
          bio origin key download -s biome

      - name: Setup Studio and Tools
        env:
          HAB_ORIGIN: biome
          HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
          HAB_STUDIO_SECRET_HAB_BLDR_CHANNEL: LTS-2024
        run: |
           for i in {1..3}; do
             bio studio run 'make -f ci/Makefile setup' && success=true && break || sleep 10
           done
           if [ "$success" != "true" ]; then
             echo "Failed to setup studio"
             exit 1
           fi

      - name: Build and Package
        env:
          HAB_ORIGIN: biome
          HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
          HAB_STUDIO_SECRET_HAB_BLDR_CHANNEL: LTS-2024
        run: |
          bio studio run 'make -f ci/Makefile all dist upload'

      - name: Get package info
        run: |
          cat results/bio.env >> $GITHUB_ENV

      - name: Upload Linux Biome
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: results/${{ env.pkg_name }}-${{ env.pkg_version }}-${{ env.pkg_target }}.tar.gz
          asset_name: ${{ env.pkg_name }}-${{ env.pkg_version }}-${{ env.pkg_target }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux Metadata
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: results/meta-${{ env.pkg_version }}-${{ env.pkg_target }}.tar.gz
          asset_name: meta-${{ env.pkg_version }}-${{ env.pkg_target }}.tar.gz
          asset_content_type: application/gzip

      - name: Promote to testing
        env:
          HAB_ORIGIN: biome
          HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
        run: |
          bio studio run 'make -f ci/Makefile promote-testing'

  # package-darwin:
  #   runs-on: darwin-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install MacOS Biome
  #       run: |
  #         curl https://raw.githubusercontent.com/biome-sh/biome/master/components/bio/install-darwin.sh | sudo bash

  #     - name: Install Signing Keys
  #       run: |
  #         bio origin key download biome
  #         bio origin key download -s -z $HAB_AUTH_TOKEN biome

  #     # - name: Setup Studio and Tools
  #     #   run: |
  #     #     bio studio run 'make -f ci/Makefile.darwin setup'

  #     - name: Build and Package
  #       run: |
  #         bio studio run 'make -f ci/Makefile.darwin all dist'

  #     - name: Get package info
  #       run: |
  #         cat results/bio.env | sed 's/\(.*\)=\(.*\)/::set-env name=\1::\2/'

  #     - name: Upload Darwin Biome
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ github.event.release.upload_url }}
  #         asset_path: results/$pkg_name-$pkg_version-$pkg_target.zip
  #         asset_name: $pkg_name-$pkg_version-$pkg_target.zip

  #     - name: Promote to stable
  #       run: |
  #         bio studio run 'make -f ci/Makefile.darwin promote-stable'

  # package-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install Windows Biome
  #       run: |
  #         Set-ExecutionPolicy Bypass -Scope Process -Force
  #         iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/biome-sh/biome/master/components/bio/install-windows.ps1'))

  #     - name: Install Signing Keys
  #       run: |
  #         bio.exe origin key download biome
  #         bio.exe origin key download -s -z $HAB_AUTH_TOKEN biome

  #     # - name: Setup Studio and Tools
  #     #   run: |
  #     #     bio.exe studio run 'make -f ci/Makefile.windows setup'

  #     - name: Build and Package
  #       run: |
  #         bio.exe studio run 'make -f ci/Makefile.windows build dist upload'

  #     - name: Get package info
  #       run: |
  #         Get-Content results/bio.env | sed 's/\(.*\)=\(.*\)/::set-env name=\1::\2/'

  #     - name: Upload Windows Biome
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ github.event.release.upload_url }}
  #         asset_path: results/$pkg_name-$pkg_version-$pkg_target.zip
  #         asset_name: $pkg_name-$pkg_version-$pkg_target.zip

  #     - name: Promote to stable
  #       run: |
  #         bio studio run 'make -f ci/Makefile.windows promote-testing'

